import { documentPage } from '../scripts/simulator.js';
export const data = { permalink: 'photography/index.html' };
const priorities = [
  { number: '01', title: 'Admission & campus welcome', label: 'First priority', subject: 'Students in recognizable campus settings: arrival, gathering, or moving through a learning space.', modules: 'Admission congratulations, college welcome, campus introduction, existing desktop/mobile photo sections.', purpose: 'Make the welcome feel personal and connected to the applicant’s campus.', crop: 'Landscape original with room around the subject for a wide or compact crop.', layout: 'A wide image paired with the welcome message, or a campus image in the sidebar.' },
  { number: '02', title: 'College community & faculty', label: 'First priority', subject: 'Current faculty portraits, students collaborating, and approved stills from community and program-director videos.', modules: 'Khoury campus welcome, faculty/staff introductions, program-director messages, other college content blocks.', purpose: 'Introduce the people applicants will learn with and help distinguish each college.', crop: 'Landscape video thumbnails plus portraits with enough space for square crops.', layout: 'Image and text pairs or a small group of video cards with clear titles.' },
  { number: '03', title: 'Experiential learning & co-op', label: 'Next priority', subject: 'Students working in labs, on real projects, or with industry partners. Favor activity specific to the program.', modules: 'Experiential Learning and Co-op, research and college opportunity content.', purpose: 'Show what learning at Northeastern looks like in practice.', crop: 'Landscape images that retain the activity and people when cropped.', layout: 'An editorial image beside the supporting copy, with a clear resource link.' },
  { number: '04', title: 'Enrollment support', label: 'Next priority', subject: 'Approachable counselors and students in conversation, including international enrollment support.', modules: 'Global Enrollment Support and college support/contact blocks.', purpose: 'Give applicants a human connection when they need guidance.', crop: 'Landscape or square-friendly originals with natural, uncluttered backgrounds.', layout: 'A compact photograph above or alongside contact information.' },
];
export default function () {
  return documentPage('Photography planning — Slate simulator', `
<header class="sim-bar"><strong>Photography planning</strong><nav aria-label="Tools"><a href="/views/">View simulator</a><a href="/modules/">Module library</a><a href="/references/">References</a></nav></header>
<main class="photo-plan">
  <section class="photo-plan-intro"><p class="photo-eyebrow">Northeastern graduate portal</p><h1>Photography with a purpose.</h1><p>Use imagery to welcome applicants, introduce their community, and show the opportunities ahead. Gather the assets first; final module placement and crops will be decided after review.</p><span class="photo-plan-status">Awaiting photography · placements proposed</span></section>
  <section aria-labelledby="photo-priorities"><h2 id="photo-priorities">What to request first</h2><p>These four groups offer the strongest opportunities for the current modules. The treatments below describe possibilities, not approved placements.</p>
  <div class="photo-priority-grid">${priorities.map(p => `<article class="photo-priority"><div class="photo-priority-top"><span class="photo-number">${p.number}</span><span class="photo-eyebrow">${p.label}</span></div><h3>${p.title}</h3><p>${p.purpose}</p><dl><dt>Photography to request</dt><dd>${p.subject}</dd><dt>Candidate modules</dt><dd>${p.modules}</dd><dt>Useful format</dt><dd>${p.crop}</dd><dt>Possible composition</dt><dd>${p.layout}</dd></dl><p class="photo-awaiting">Images to be supplied</p></article>`).join('')}</div></section>
  <section class="photo-request" aria-labelledby="photo-delivery"><h2 id="photo-delivery">Include with each image</h2><ul><li>Full-resolution original files, preferably without embedded text or logos.</li><li>Campus, college, program, and subject identification where available.</li><li>Confirmation that the image is approved for use in the graduate applicant portal, with any credit or usage restrictions.</li><li>A short description of the scene to help write accurate alt text.</li><li>Flexible framing and alternate images so we can test desktop and mobile crops.</li></ul><p>For video modules, request a working video URL and an approved thumbnail. Supply a caption or title separately from the image.</p></section>
  <section class="photo-plan-notes" aria-labelledby="photo-review"><div><h2 id="photo-review">When the assets arrive</h2><ol><li>Review relevance, permissions, image quality, and campus/college accuracy.</li><li>Shortlist images against the candidate modules above.</li><li>Try compositions and crops at desktop and mobile widths.</li><li>Confirm placement, alt text, and loading behavior before implementation.</li></ol></div><div><h2>Keep essential tasks easy to reach</h2><p>Payments, checklists, uploads, forms, and application details should remain compact. Concentrate photography in welcome, community, opportunities, and support sections.</p><p>Existing broken image slots and oversized college wordmarks also need review. Wordmarks are branding assets and should be sized separately from photography.</p></div></section>
</main>`, 'simulator');
}
